<package format="2">
  <name>arm_controller</name>
  <version>0.0.1</version>
  <description>Arm controller messages</description>
  <maintainer email="dev@reinovo.com">reinovo</maintainer>
  <license>AGPL</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
</package>
